import { db } from "./db";
import { products, discountCodes, stores } from "@shared/schema";

const SEED_PRODUCTS = [
  {
    nameEn: "Elegant Maroon Abaya with Gold Embroidery",
    nameAr: "عباية ماروني أنيقة بتطريز ذهبي",
    descriptionEn: "A stunning maroon abaya adorned with intricate gold thread embroidery along the sleeves and hemline. Handcrafted with premium fabric for a luxurious drape and feel.",
    descriptionAr: "عباية ماروني مذهلة مزينة بتطريز دقيق بخيوط ذهبية على الأكمام والحاشية. مصنوعة يدوياً من أقمشة فاخرة لانسيابية وملمس فاخر.",
    price: 89900,
    originalPrice: 112000,
    category: "abayas",
    subcategory: "embroidered",
    images: ["/images/product1.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Maroon & Gold", "Black & Gold", "Navy & Silver"],
    fabricEn: "Premium crepe with hand embroidery",
    fabricAr: "كريب فاخر مع تطريز يدوي",
    inStock: true,
    featured: true,
    badge: "الأكثر مبيعاً",
    rating: 4.9,
    reviewCount: 156,
  },
  {
    nameEn: "Classic Black Abaya with Pearl Details",
    nameAr: "عباية سوداء كلاسيكية بتفاصيل لؤلؤية",
    descriptionEn: "A timeless black abaya featuring delicate pearl embellishments along the front panel and cuffs. Perfect for everyday elegance and special occasions alike.",
    descriptionAr: "عباية سوداء خالدة تتميز بزخارف لؤلؤية رقيقة على اللوحة الأمامية والأساور. مثالية للأناقة اليومية والمناسبات الخاصة.",
    price: 75000,
    originalPrice: null,
    category: "abayas",
    subcategory: "classic",
    images: ["/images/product2.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black & Pearl", "Dark Navy & Pearl", "Charcoal & Silver"],
    fabricEn: "Korean nida with pearl accents",
    fabricAr: "نيدا كوري مع لمسات لؤلؤية",
    inStock: true,
    featured: true,
    badge: "جديد",
    rating: 4.8,
    reviewCount: 89,
  },
  {
    nameEn: "Luxury Jalabiya - Emerald Collection",
    nameAr: "جلابية فاخرة - مجموعة الزمرد",
    descriptionEn: "An exquisite emerald green jalabiya with elaborate gold and crystal beadwork. The flowing silhouette with bell sleeves creates a regal, sophisticated look.",
    descriptionAr: "جلابية زمردية رائعة مع أعمال خرز ذهبية وكريستالية متقنة. القصة الانسيابية مع الأكمام الجرسية تخلق إطلالة ملكية وراقية.",
    price: 125000,
    originalPrice: null,
    category: "jalabiyas",
    subcategory: "luxury",
    images: ["/images/product3.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald & Gold", "Royal Blue & Gold", "Burgundy & Gold"],
    fabricEn: "Premium chiffon with crystal beading",
    fabricAr: "شيفون فاخر مع خرز كريستالي",
    inStock: true,
    featured: true,
    badge: "حصري",
    rating: 5.0,
    reviewCount: 67,
  },
  {
    nameEn: "Floral Print Casual Dress",
    nameAr: "فستان كاجوال بطبعة زهور",
    descriptionEn: "A beautiful casual dress with vibrant floral prints, perfect for daily wear. Comfortable fabric with a modern cut that flatters every body type.",
    descriptionAr: "فستان كاجوال جميل بطبعات زهرية نابضة بالحياة، مثالي للارتداء اليومي. قماش مريح بقصة عصرية تناسب كل الأجسام.",
    price: 35000,
    originalPrice: 45000,
    category: "dresses",
    subcategory: "casual",
    images: ["/images/product4.jpg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Pink Floral", "Blue Floral", "Green Floral"],
    fabricEn: "Cotton blend with stretch",
    fabricAr: "مزيج قطني مع مطاطية",
    inStock: true,
    featured: true,
    badge: "تخفيض",
    rating: 4.7,
    reviewCount: 203,
  },
  {
    nameEn: "Bridal Henna Night Set",
    nameAr: "طقم ليلة الحناء للعروس",
    descriptionEn: "A magnificent set designed for the henna night celebration. Includes an embroidered kaftan with matching accessories, all in stunning rose gold tones.",
    descriptionAr: "طقم رائع مصمم لاحتفال ليلة الحناء. يتضمن كفتان مطرز مع إكسسوارات متناسقة، كلها بدرجات الروز جولد المذهلة.",
    price: 185000,
    originalPrice: null,
    category: "bridal",
    subcategory: "henna",
    images: ["/images/product5.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rose Gold", "Gold & Ivory", "Champagne"],
    fabricEn: "Silk organza with hand beading",
    fabricAr: "أورجانزا حرير مع تخريز يدوي",
    inStock: true,
    featured: true,
    badge: "فاخر",
    rating: 5.0,
    reviewCount: 45,
  },
  {
    nameEn: "Kids Eid Jalabiya - Princess Collection",
    nameAr: "جلابية عيد للأطفال - مجموعة الأميرات",
    descriptionEn: "An adorable Eid jalabiya for little princesses, crafted from soft fabrics with sparkling embroidery. Comfortable and stylish for celebrations.",
    descriptionAr: "جلابية عيد رائعة للأميرات الصغيرات، مصنوعة من أقمشة ناعمة مع تطريز لامع. مريحة وأنيقة للاحتفالات.",
    price: 28000,
    originalPrice: null,
    category: "kids",
    subcategory: "eid",
    images: ["/images/product6.jpg"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Mint & Gold", "Baby Pink & Silver", "Lilac & Gold"],
    fabricEn: "Organic cotton with gentle embroidery",
    fabricAr: "قطن عضوي مع تطريز ناعم",
    inStock: true,
    featured: false,
    badge: "العيد",
    rating: 4.9,
    reviewCount: 178,
  },
  {
    nameEn: "Masah Gift Box - Premium",
    nameAr: "صندوق هدايا ماسـة - فاخر",
    descriptionEn: "A beautifully curated premium gift box featuring a silk shawl, pearl jewelry set, and luxury oud perfume, all presented in our signature Masah packaging.",
    descriptionAr: "صندوق هدايا فاخر منسق بعناية يتضمن شال حرير وطقم مجوهرات لؤلؤي وعطر عود فاخر، الكل مقدم في تغليف ماسـة المميز.",
    price: 95000,
    originalPrice: null,
    category: "gifts",
    subcategory: "premium",
    images: ["/images/product7.jpg"],
    sizes: ["One Size"],
    colors: ["Gold & Pearl", "Rose Gold & Pearl", "Silver & Pearl"],
    fabricEn: "Pure silk shawl included",
    fabricAr: "يتضمن شال حرير نقي",
    inStock: true,
    featured: true,
    badge: "هدية",
    rating: 5.0,
    reviewCount: 112,
  },
  {
    nameEn: "Embroidered Linen Summer Abaya",
    nameAr: "عباية كتان صيفية مطرزة",
    descriptionEn: "A lightweight linen abaya perfect for summer, featuring colorful floral embroidery. Breathable and stylish for warm weather outings.",
    descriptionAr: "عباية كتان خفيفة مثالية للصيف، تتميز بتطريز زهري ملون. قابلة للتنفس وأنيقة للخروجات في الطقس الدافئ.",
    price: 62000,
    originalPrice: 78000,
    category: "abayas",
    subcategory: "summer",
    images: ["/images/product8.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige & Multi", "White & Pastel", "Sand & Floral"],
    fabricEn: "Premium linen with cotton lining",
    fabricAr: "كتان فاخر مع بطانة قطنية",
    inStock: true,
    featured: false,
    badge: "صيفي",
    rating: 4.6,
    reviewCount: 134,
  },
  {
    nameEn: "Evening Gown - Royal Collection",
    nameAr: "فستان سهرة - المجموعة الملكية",
    descriptionEn: "A breathtaking evening gown in deep navy with silver threadwork and Swarovski crystal embellishments. Perfect for weddings and formal occasions.",
    descriptionAr: "فستان سهرة أخاذ بلون النيفي العميق مع أعمال خيوط فضية وزخارف كريستال سواروفسكي. مثالي لحفلات الزفاف والمناسبات الرسمية.",
    price: 220000,
    originalPrice: null,
    category: "dresses",
    subcategory: "evening",
    images: ["/images/product9.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy & Silver", "Black & Gold", "Burgundy & Crystal"],
    fabricEn: "Italian silk with Swarovski crystals",
    fabricAr: "حرير إيطالي مع كريستال سواروفسكي",
    inStock: true,
    featured: true,
    badge: "ملكي",
    rating: 5.0,
    reviewCount: 38,
  },
  {
    nameEn: "Pastel Crepe Everyday Abaya",
    nameAr: "عباية كريب باستيل يومية",
    descriptionEn: "A modern everyday abaya in soft pastel tones with minimalist design. Features hidden pockets and a relaxed fit for ultimate comfort.",
    descriptionAr: "عباية يومية عصرية بألوان باستيل ناعمة بتصميم بسيط. تتميز بجيوب مخفية وقصة مريحة لراحة مطلقة.",
    price: 42000,
    originalPrice: null,
    category: "abayas",
    subcategory: "everyday",
    images: ["/images/product10.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Dusty Rose", "Sage Green", "Powder Blue", "Lavender"],
    fabricEn: "Premium Korean crepe",
    fabricAr: "كريب كوري فاخر",
    inStock: true,
    featured: false,
    badge: null,
    rating: 4.8,
    reviewCount: 267,
  },
];

const SEED_DISCOUNTS = [
  {
    code: "MASAH10",
    type: "percentage",
    value: 10,
    minOrder: 10000,
    maxUses: 1000,
    active: true,
  },
  {
    code: "EID25",
    type: "percentage",
    value: 25,
    minOrder: 20000,
    maxUses: 500,
    active: true,
  },
  {
    code: "FREESHIP",
    type: "fixed",
    value: 1500,
    minOrder: 15000,
    maxUses: null,
    active: true,
  },
];

const SEED_STORES = [
  {
    nameEn: "Masah Boutique - Saihat Main Store",
    nameAr: "بوتيك ماسـة - فرع سيهات الرئيسي",
    addressEn: "Near the Roundabout, Saihat, Eastern Province",
    addressAr: "عند الدوار، سيهات، المنطقة الشرقية",
    city: "Saihat",
    phone: "+966 50 000 0000",
    hoursEn: "Sat-Thu: 10AM-10PM, Fri: 4PM-10PM",
    hoursAr: "السبت-الخميس: 10ص-10م، الجمعة: 4م-10م",
    mapUrl: "https://maps.google.com/?q=26.4833,50.0333",
    isActive: true,
  },
  {
    nameEn: "Masah Boutique - Qatif Branch",
    nameAr: "بوتيك ماسـة - فرع القطيف",
    addressEn: "Qatif Corniche, Qatif, Eastern Province",
    addressAr: "كورنيش القطيف، القطيف، المنطقة الشرقية",
    city: "Qatif",
    phone: "+966 50 000 0001",
    hoursEn: "Sat-Thu: 10AM-10PM, Fri: 4PM-10PM",
    hoursAr: "السبت-الخميس: 10ص-10م، الجمعة: 4م-10م",
    mapUrl: "https://maps.google.com/?q=26.5196,50.0115",
    isActive: true,
  },
  {
    nameEn: "Masah Boutique - Dammam Branch",
    nameAr: "بوتيك ماسـة - فرع الدمام",
    addressEn: "Al Shatea Mall, Dammam, Eastern Province",
    addressAr: "مجمع الشاطئ، الدمام، المنطقة الشرقية",
    city: "Dammam",
    phone: "+966 50 000 0002",
    hoursEn: "Sat-Thu: 10AM-10PM, Fri: 4PM-10PM",
    hoursAr: "السبت-الخميس: 10ص-10م، الجمعة: 4م-10م",
    mapUrl: "https://maps.google.com/?q=26.4207,50.0888",
    isActive: true,
  },
];

export async function seedDatabase() {
  try {
    const existingProducts = await db.select().from(products);
    if (existingProducts.length === 0) {
      console.log("Seeding database with Masah Boutique products...");
      await db.insert(products).values(SEED_PRODUCTS);
      console.log(`Seeded ${SEED_PRODUCTS.length} products`);

      await db.insert(discountCodes).values(SEED_DISCOUNTS);
      console.log(`Seeded ${SEED_DISCOUNTS.length} discount codes`);
    } else {
      console.log(`Database already has ${existingProducts.length} products, skipping seed`);
    }

    const existingStores = await db.select().from(stores);
    if (existingStores.length === 0) {
      console.log("Seeding database with stores...");
      await db.insert(stores).values(SEED_STORES);
      console.log(`Seeded ${SEED_STORES.length} stores`);
    } else {
      console.log(`Database already has ${existingStores.length} stores, skipping seed`);
    }
  } catch (error) {
    console.error("Seed error:", error);
  }
}
